# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZWM4YjZlOWIzYTlkNjQzZGVhNWQ0NjM0NjY1MjM3MzliNmQzOTY5N2YzNGJkNTgwOGNlYzY2Y2FiMmVhNDJkYjM5YmEwMWNhYTlmNzUyMDY5NWEyNWYzNmJhM2RmZjQ4NTYxYjUxY2NiZjQxMGNkNzM4ZDc3NGM2OGYwNzI5ZjQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
